version: "3.9"

services:
  proxy:
    image: hello-cloud-proxy:v1.0.0
    build:
      context: ./proxy
    ports:
      - "8080:80"

  frontend:
    image: hello-cloud-frontend:v1.0.0
    build:
      context: ./packages/frontend
      dockerfile: deploy/Dockerfile
    ports:
      - "5000:80"

  backend:
    image: hello-cloud-backend:v1.0.0
    build:
      context: ./packages/backend
      dockerfile: deploy/Dockerfile
    ports:
      - "3000:3000"
    environment:
      CORS_ORIGINS: http://frontend:5000
